// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF6zO9Er8L_sb4wWELaxS1eW2CCmDkDoo',
    appId: '1:802542245005:web:2532e4f63f2bfa7d97bec4',
    messagingSenderId: '802542245005',
    projectId: 'vetadvisor-2d900',
    authDomain: 'vetadvisor-2d900.firebaseapp.com',
    storageBucket: 'vetadvisor-2d900.appspot.com',
    measurementId: 'G-98SX0QK005',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuzJIG3fB4bJ8dKJ0Wb44fk7z1JrlOmT8',
    appId: '1:802542245005:android:d2b4b4966f93b8df97bec4',
    messagingSenderId: '802542245005',
    projectId: 'vetadvisor-2d900',
    storageBucket: 'vetadvisor-2d900.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsqLreI83Q0sGhAt8rDiOhdBx7mF2wEKY',
    appId: '1:802542245005:ios:e7e625ee1fbf0b8597bec4',
    messagingSenderId: '802542245005',
    projectId: 'vetadvisor-2d900',
    storageBucket: 'vetadvisor-2d900.appspot.com',
    androidClientId: '802542245005-ltmnbn7t8jqej8s7nr8etg6mn8ublfo9.apps.googleusercontent.com',
    iosClientId: '802542245005-gns5ck7u7ftckg5kbdlpt4jbd6kms08p.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetadvisor',
  );
}
